# site settings
title: Overload 2018 #Forty
subtitle: # Overload 2018by HTML5 UP
email:  Overload@gmail.com # youremailaddress@gmail.com
description: Bienvenido al evento anual de cultura alternativa más grande de Bolivia #A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/2018Overload" # the subpath of your site, e.g. /blog
url: "https://kennetps.github.io/" # the base hostname & protocol for your site
author:
street_address: Recinto Ferial Alalay # 1234 Somewhere Road
city: Cochabamba #Nashville
state: Cb #TN
zip_code: 00000 #55555
country: Bolivia # United States of America
phone: 70100000 # (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 7

# social settings
500px_url:
facebook_url: https://www.facebook.com/events/498350663917773/
github_url:
gitlab_url: # https://gitlab.com/u/andrewbanchich
googleplus_url: # https://plus.google.com/u/0/+AndrewBanchich
instagram_url: # https://instagram.com
linkedin_url: # https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: # https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
